import { AppModel } from '../models/app-model.js';

// La Vista centraliza la creación de enlaces para que cada CTA use el mismo número.
const whatsappUrl = (text) => `https://wa.me/${AppModel.state.whatsappNumber}?text=${encodeURIComponent(text)}`;
// El texto escrito por la persona vuelve a mostrarse en un <textarea>; se escapa
// antes de interpolarlo para que nunca sea interpretado como HTML.
const escapeHtml = (value) => value.replace(/[&<>\"']/g, (character) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
}[character]));
// Clases explícitas: Tailwind puede detectarlas sin depender de nombres dinámicos.
const badgeClasses = {
    emerald: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
    blue: 'bg-blue-500/10 text-blue-400 border-blue-500/30',
    purple: 'bg-purple-500/10 text-purple-400 border-purple-500/30',
    amber: 'bg-amber-500/10 text-amber-400 border-amber-500/30'
};
const contactEmailUrl = 'mailto:forge.look19@gmail.com';
const socialLinksMarkup = (className = 'inline-flex h-5 w-5 items-center justify-center text-brand-500 hover:text-brand-600 transition-colors') => AppModel.socialLinks.map((social) => `<a href="${social.href}" target="_blank" rel="noopener noreferrer" aria-label="${social.name}" class="${className}"><i class="${social.icon}"></i></a>`).join('');

/** VISTA: renderiza HTML; no decide ni modifica el estado de negocio. */
export const AppView = {
    /** Encabezado que se vuelve a pintar al abrir o cerrar el menú móvil. */
    renderHeader() {
        const { isMenuOpen } = AppModel.state;
        document.querySelector('#header-container').innerHTML = `<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">
            <a href="#inicio" class="flex items-center gap-3 group"><div class="w-10 h-10 rounded-xl bg-brand-500 flex items-center justify-center text-slate-950 font-black text-xl group-hover:scale-105 transition-transform"><i class="fa-solid fa-lock text-base"></i></div><div><span class="text-xl font-bold text-white">Forge<span class="text-brand-500">Lock</span></span><span class="block text-[10px] text-slate-400 tracking-wider uppercase">Tecnología & Negocios</span></div></a>
            <nav class="hidden md:flex items-center gap-8">${AppModel.navLinks.map((link) => `<a href="${link.href}" class="text-sm font-medium text-slate-300 hover:text-brand-500 transition-colors">${link.name}</a>`).join('')}</nav>
            <a href="${whatsappUrl('Hola, me comunico desde ForgeLock y quiero hablar sobre una solución tecnológica.')}" target="_blank" rel="noopener noreferrer" class="hidden md:inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-brand-500 hover:bg-brand-600 text-slate-950 font-semibold text-sm"><i class="fa-brands fa-whatsapp text-lg"></i>Hablar por WhatsApp</a>
            <button id="mobile-menu-btn" class="md:hidden text-slate-300 p-2 text-xl" aria-label="Abrir menú"><i class="fa-solid ${isMenuOpen ? 'fa-xmark' : 'fa-bars'}"></i></button></div>
            <div class="${isMenuOpen ? 'block' : 'hidden'} md:hidden bg-slate-900 border-b border-slate-800 px-4 pt-2 pb-6 space-y-3" id="mobile-menu">${AppModel.navLinks.map((link) => `<a href="${link.href}" class="mobile-nav-link block py-2.5 px-4 rounded-lg text-base text-slate-200 hover:bg-slate-800">${link.name}</a>`).join('')}<a href="${whatsappUrl('Hola, me comunico desde ForgeLock.')}" target="_blank" class="flex items-center justify-center gap-2 px-5 py-3 rounded-xl bg-brand-500 text-slate-950 font-semibold"><i class="fa-brands fa-whatsapp"></i>Hablar por WhatsApp</a></div>`;
    },

    renderHero() {
        document.querySelector('#hero-container').innerHTML = `<div id="inicio" class="relative pt-16 pb-24 md:pt-24 md:pb-32 overflow-hidden"><div class="absolute top-1/4 left-1/2 -translate-x-1/2 w-[500px] h-[500px] bg-brand-500/10 rounded-full blur-3xl pointer-events-none"></div><div class="max-w-7xl mx-auto px-4 relative z-10"><div class="max-w-3xl mx-auto text-center space-y-8"><span class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-slate-900 border border-slate-800 text-brand-400 text-sm"><span class="w-2 h-2 rounded-full bg-brand-500 animate-pulse"></span>Soluciones tecnológicas sin complicaciones</span><h1 class="text-4xl sm:text-6xl font-extrabold text-white leading-tight">Soluciones tecnológicas que hacen <span class="text-brand-400">crecer tu negocio</span></h1><p class="text-lg sm:text-xl text-slate-300 leading-relaxed">Automatizamos procesos, desarrollamos sistemas y creamos herramientas digitales adaptadas a las necesidades reales de tu empresa.</p><div class="flex flex-col sm:flex-row justify-center gap-4"><a href="#soluciones" class="px-8 py-4 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-semibold text-center border border-slate-700">Ver soluciones</a><a href="${whatsappUrl('Hola, vi la página de ForgeLock y quiero hablar sobre una solución.')}" target="_blank" class="px-8 py-4 rounded-xl bg-brand-500 hover:bg-brand-600 text-slate-950 font-bold text-center"><i class="fa-brands fa-whatsapp mr-2"></i>Hablar por WhatsApp</a></div></div></div></div>`;
    },

    /** Carrusel de soluciones; recibe su elemento activo desde el Modelo. */
    renderSolutions() {
        const active = AppModel.featuredSolutions[AppModel.state.activeBannerIndex];
        document.querySelector('#solutions-carousel-container').innerHTML = `<div id="soluciones" class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div class="text-center max-w-3xl mx-auto mb-12 space-y-4"><span class="text-brand-400 text-xs uppercase tracking-widest font-bold">Nuestras soluciones destacadas</span><h2 class="text-3xl sm:text-4xl font-bold text-white">¿Qué podemos construir para tu negocio?</h2><p class="text-slate-400">Explora soluciones diseñadas para resolver problemas reales del día a día.</p></div><div class="grid grid-cols-2 md:grid-cols-4 gap-3 mb-8">${AppModel.featuredSolutions.map((solution, index) => `<button data-banner="${index}" class="solution-card-transition p-4 rounded-2xl text-left border ${index === AppModel.state.activeBannerIndex ? 'bg-slate-900 border-brand-500/60' : 'bg-slate-900/40 border-slate-800 hover:border-slate-700 hover:bg-slate-900/70'}"><i class="${solution.icon} text-brand-400 text-xl"></i><span class="block mt-3 text-sm font-semibold text-white">${solution.title}</span></button>`).join('')}</div><div class="bg-gradient-to-br from-slate-900 to-slate-950 border border-slate-800 rounded-3xl p-6 sm:p-10"><div class="grid lg:grid-cols-12 gap-8 items-center"><div class="lg:col-span-7 space-y-5"><span class="inline-flex px-3 py-1 rounded-full ${badgeClasses[active.tone]} border text-xs font-semibold">${active.tag}</span><h3 class="text-2xl sm:text-3xl font-bold text-white">${active.title}</h3><p class="text-slate-300 text-lg leading-relaxed">${active.description}</p><div class="grid sm:grid-cols-2 gap-3">${active.highlights.map((item) => `<div class="text-sm text-slate-300 bg-slate-900 px-3 py-2 rounded-xl border border-slate-800"><i class="fa-solid fa-check text-brand-500 mr-2"></i>${item}</div>`).join('')}</div><a href="${whatsappUrl(active.whatsappText)}" target="_blank" rel="noopener noreferrer" class="inline-flex items-center gap-2 px-6 py-3.5 rounded-xl bg-brand-500 text-slate-950 font-bold"><i class="fa-brands fa-whatsapp text-lg"></i>Quiero esta solución</a></div><div class="lg:col-span-5 bg-slate-950/60 p-6 rounded-2xl border border-slate-800 min-h-[240px] flex flex-col justify-center"><i class="${active.icon} text-brand-400 text-5xl mb-5"></i><h4 class="text-white font-bold">¿Te interesa esto?</h4><p class="text-sm text-slate-400 mt-2">Conversemos por WhatsApp en segundos.</p></div></div></div></div>`;
    },

    renderNeedFinder() {
        document.querySelector('#need-finder-container').innerHTML = '<div id="idea-generator-container" class="max-w-7xl mx-auto px-4"></div>';
    },

    renderServices() { document.querySelector('#services-container').innerHTML = `<div id="servicios" class="max-w-7xl mx-auto px-4"><div class="text-center max-w-3xl mx-auto mb-12"><span class="text-brand-400 text-xs uppercase tracking-widest font-bold">Capacidades técnicas</span><h2 class="text-3xl sm:text-4xl font-bold text-white mt-4">Nuestros principales servicios</h2></div><div class="grid md:grid-cols-2 lg:grid-cols-3 gap-6">${AppModel.services.map(([title, desc, icon]) => `<article class="bg-slate-900/60 border border-slate-800 rounded-2xl p-6"><i class="${icon} text-brand-400 text-2xl"></i><h3 class="text-xl font-bold text-white mt-5">${title}</h3><p class="text-slate-400 text-sm leading-relaxed mt-3">${desc}</p><a href="${whatsappUrl(`Hola, me interesa el servicio de ${title}.`)}" target="_blank" class="inline-flex gap-2 text-sm font-semibold text-brand-400 mt-6">Consultar por WhatsApp <i class="fa-solid fa-arrow-right text-xs"></i></a></article>`).join('')}</div></div>`; },

    renderWorkflow() { document.querySelector('#workflow-container').innerHTML = `<div id="proceso" class="max-w-7xl mx-auto px-4"><div class="text-center max-w-3xl mx-auto mb-12"><span class="text-brand-400 text-xs uppercase tracking-widest font-bold">Paso a paso</span><h2 class="text-3xl sm:text-4xl font-bold text-white mt-4">¿Cómo trabajamos contigo?</h2></div><div class="grid md:grid-cols-2 lg:grid-cols-4 gap-6">${AppModel.workflow.map(([step, title, desc]) => `<article class="bg-slate-900 border border-slate-800 rounded-2xl p-6"><span class="inline-flex w-10 h-10 rounded-xl bg-brand-500 text-slate-950 font-black items-center justify-center">${step}</span><h3 class="text-xl font-bold text-white mt-5">${title}</h3><p class="text-slate-400 text-sm leading-relaxed mt-3">${desc}</p></article>`).join('')}</div></div>`; },

    renderHelpAndCta() { document.querySelector('#help-banner-container').innerHTML = `<div class="max-w-7xl mx-auto px-4"><div class="bg-slate-900 border border-slate-800 rounded-3xl p-8 sm:p-12 flex flex-col lg:flex-row items-center justify-between gap-8"><div class="max-w-2xl"><span class="text-brand-400 text-sm">¿Dudas sobre qué elegir?</span><h3 class="text-2xl sm:text-3xl font-bold text-white mt-4">¿No sabes exactamente qué necesitas?</h3><p class="text-slate-300 mt-4">Explícanos cómo funciona tu negocio y te ayudamos a convertir esa necesidad en una solución.</p></div><a href="${whatsappUrl('Hola, no estoy seguro de qué solución necesito. ¿Me ayudan?')}" target="_blank" class="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-brand-500 text-slate-950 font-bold whitespace-nowrap"><i class="fa-brands fa-whatsapp text-xl"></i>Contar mi idea</a></div></div>`; document.querySelector('#cta-container').innerHTML = `<div id="contacto" class="max-w-5xl mx-auto px-4 text-center space-y-6"><span class="text-brand-400">Iniciemos hoy mismo</span><h2 class="text-3xl sm:text-5xl font-black text-white">¿Tienes una idea? Hagámosla realidad.</h2><p class="text-slate-300 text-lg">Cuéntanos qué quieres mejorar en tu negocio.</p><a href="${whatsappUrl('Hola, quiero hablar con un asesor de ForgeLock.')}" target="_blank" class="inline-flex items-center gap-3 px-8 py-4 rounded-xl bg-brand-500 text-slate-950 font-bold text-lg"><i class="fa-brands fa-whatsapp text-2xl"></i>Hablar por WhatsApp</a></div>`; },

    renderFooter() { document.querySelector('#footer-container').innerHTML = `<div class="max-w-7xl mx-auto px-4"><div class="grid md:grid-cols-3 gap-8 pb-10 border-b border-slate-900"><div><span class="text-lg font-bold text-white">Forge<span class="text-brand-500">Lock</span></span><p class="text-xs text-slate-400 mt-4">Soluciones tecnológicas para negocios y empresas.</p></div><div><h4 class="text-sm font-semibold text-white uppercase">Enlaces</h4><div class="flex flex-col gap-2 mt-3 text-sm">${AppModel.navLinks.map((link) => `<a href="${link.href}" class="hover:text-brand-400">${link.name}</a>`).join('')}</div></div><div><h4 class="text-sm font-semibold text-white uppercase">Contacto directo</h4><div class="flex flex-col gap-3 mt-3 text-sm"><a href="${whatsappUrl('Hola, quiero contactar a ForgeLock.')}" target="_blank" rel="noopener noreferrer" aria-label="Contactar a ForgeLock por WhatsApp" class="flex items-center gap-2 hover:text-brand-400"><i class="fa-brands fa-whatsapp text-brand-500 text-base w-5 text-center"></i><span>304 340 2589</span></a><a href="${contactEmailUrl}" aria-label="Enviar correo a ForgeLock" class="flex items-center gap-2 hover:text-brand-400"><i class="fa-solid fa-envelope text-brand-500 text-base w-5 text-center"></i><span>forge.look19@gmail.com</span></a><div class="flex items-center gap-2"><i class="fa-solid fa-share-nodes text-brand-500 text-base w-5 text-center" aria-hidden="true"></i><span class="whitespace-nowrap">Síguenos en</span><div class="flex items-center gap-2 ml-1">${socialLinksMarkup()}</div></div></div></div></div><p class="pt-8 text-xs">© ${new Date().getFullYear()} ForgeLock. Todos los derechos reservados.</p></div>`; },

    showToast(message) { const toast = document.createElement('div'); toast.className = 'bg-slate-900 border border-brand-500/40 text-slate-100 px-4 py-3 rounded-xl shadow-2xl pointer-events-auto'; toast.textContent = message; document.querySelector('#toast-container').append(toast); setTimeout(() => toast.remove(), 4000); }
};
